//
// Copyright (c) 2025 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <boost/capy/cond.hpp>
#include <boost/capy/delay.hpp>
#include <boost/capy/ex/run.hpp>
#include <boost/capy/ex/run_async.hpp>
#include <boost/capy/ex/this_coro.hpp>
#include <boost/capy/task.hpp>
#include <boost/capy/timeout.hpp>
#include <boost/capy/when_any.hpp>
#include <boost/corosio/io_context.hpp>
#include <boost/corosio/signal_set.hpp>
#include <boost/describe/class.hpp>
#include <boost/json/parse.hpp>
#include <boost/json/value.hpp>
#include <boost/system/errc.hpp>
#include <boost/system/result.hpp>

#include <concepts>
#include <csignal>
#include <cstdint>
#include <iostream>
#include <ranges>
#include <span>
#include <sstream>
#include <stop_token>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

#include "nativepg/co_connection.hpp"
#include "nativepg/connect_params.hpp"
#include "nativepg/extended_error.hpp"
#include "nativepg/request.hpp"
#include "nativepg/responses/check.hpp"
#include "nativepg/responses/resultset_callback.hpp"

// Shows how to implement a listener that keeps a real-time
// up-to-date cache of a certain table.

using namespace nativepg;
namespace capy = boost::capy;
namespace corosio = boost::corosio;
using namespace std::chrono_literals;

static void print_err(const char* prefix, std::error_code err, const diagnostics& diag)
{
    // Cancellation is how a clean shutdown reaches us, so it's not worth reporting
    if (err == capy::cond::canceled)
        return;

    std::cout << prefix << ": " << err << ": " << err.message();
    if (!diag.message().empty())
        std::cout << ": " << diag.message();
    std::cout << '\n';
}

struct game
{
    std::int64_t id;
    std::string name;
    std::string description;
};
BOOST_DESCRIBE_STRUCT(game, (), (id, name, description))

template <std::ranges::input_range Range>
    requires(std::same_as<std::ranges::range_value_t<Range>, game>)
static void print_games(Range&& games)
{
    std::cout << "id | name | description\n";
    for (const game& g : games)
    {
        std::cout << g.id << " | " << g.name << " | " << g.description << '\n';
    }
    std::cout << "\n\n";
}

enum class payload_type
{
    create,
    update,
    delete_,
};

struct notification_payload
{
    payload_type type;
    std::int64_t id;
};

// Parses payloads like {"type" : "update", "id" : 42}, as generated by the
// trigger in listen_cache_setup.sql
static boost::system::result<notification_payload> parse_payload(std::string_view payload)
{
    namespace json = boost::json;

    // Parse the JSON
    boost::system::error_code ec;
    auto jv = json::parse(payload, ec);
    if (ec)
        return ec;

    // We expect an object
    const auto* obj = jv.if_object();
    if (obj == nullptr)
        return make_error_code(json::error::not_object);

    // Both members should be present
    const auto* type_value = obj->if_contains("type");
    const auto* id_value = obj->if_contains("id");
    if (type_value == nullptr || id_value == nullptr)
        return make_error_code(json::error::not_found);

    // "type" is a string
    const auto* type_str = type_value->if_string();
    if (type_str == nullptr)
        return make_error_code(json::error::not_string);

    // "id" is a signed integer
    if (!id_value->is_int64())
        return make_error_code(json::error::not_int64);

    // Map the type. The trigger emits Postgres' TG_OP names, lowercased
    payload_type type{};
    if (*type_str == "insert")
        type = payload_type::create;
    else if (*type_str == "update")
        type = payload_type::update;
    else if (*type_str == "delete")
        type = payload_type::delete_;
    else
        return make_error_code(boost::system::errc::invalid_argument);

    return notification_payload{type, id_value->get_int64()};
}

static capy::io_task<> read_notifications(co_connection& conn)
{
    std::unordered_map<std::int64_t, game> games;
    diagnostics diag;
    auto update_map_handler = resultset_callback<game>([&games](game&& g) { games[g.id] = std::move(g); });

    request full_table_req;
    full_table_req.add_query("SELECT * FROM games");

    std::vector<std::int64_t> ids_to_query;

    // Query the full table first
    if (auto [exec_ec] = co_await conn.exec(full_table_req, &update_map_handler, &diag); exec_ec)
    {
        print_err("Error running initial query", exec_ec, diag);
        co_return {exec_ec};  // TODO: this is really not the best thing, as we'd be retrying endlessly
    }

    while (true)
    {
        // Print what we have
        print_games(games | std::ranges::views::values);

        // Wait for notifications
        auto [receive_ec, notifications] = co_await conn.receive();
        if (receive_ec)
        {
            print_err("Error running receive", receive_ec, {});
            co_return {receive_ec};
        }

        // Act on the notifications
        ids_to_query.clear();
        for (const auto& notif : notifications)
        {
            // We only care about notifications in games_updated
            if (notif.channel_name != "games_updated")
                continue;

            // Parse the payload
            auto parsed_payload = parse_payload(notif.payload);
            if (parsed_payload.has_error())
            {
                print_err("Received payload with invalid format", parsed_payload.error(), {});
                continue;
            }

            // Compute the action
            switch (parsed_payload->type)
            {
                case payload_type::create:
                case payload_type::update: ids_to_query.push_back(parsed_payload->id); break;
                case payload_type::delete_: games.erase(parsed_payload->id); break;
            }
        }

        // If we have IDs to re-query, do it.
        // TODO: this should really use SELECT * ... WHERE id = ANY($1),
        //   but this requires array serialization, which we don't support yet
        if (!ids_to_query.empty())
        {
            // Compose the query
            // Don't do this if your values are not ints, you will get SQL injections
            std::ostringstream oss;
            oss << "SELECT * FROM games WHERE id IN (" << ids_to_query.front();
            for (auto id : std::span<const std::int64_t>(ids_to_query).subspan(1))
                oss << ',' << id;
            oss << ')';

            // Compose the request
            request select_req;
            select_req.add_simple_query(oss.str());

            // Execute it
            if (auto [exec_ec] = co_await conn.exec(select_req, &update_map_handler, &diag); exec_ec)
            {
                print_err("Error running refresh query", exec_ec, diag);
                co_return {exec_ec};
            }
        }
    }
}

static capy::io_task<> run_listener()
{
    // Create a connection
    co_connection conn{co_await capy::this_coro::executor};

    request req;
    req.add_simple_query("LISTEN \"games_updated\"");

    connect_params conn_params{
        .hostname = "localhost",
        .username = "postgres",
        .password = "secret",
        .database = "postgres",
    };

    diagnostics diag;

    auto stop_tok = co_await capy::this_coro::stop_token;

    while (!stop_tok.stop_requested())
    {
        // Establish the connection
        if (auto [connect_ec] = co_await conn.connect(conn_params, &diag); connect_ec)
        {
            print_err("Error establishing the connection", connect_ec, diag);

            // Wait for some time before retrying.
            // Note: this will be a no-op if stop has already been requested.
            static_cast<void>(co_await capy::delay(1s));

            // Try again
            continue;
        }

        // Subscribe to the channels of interest
        if (auto [exec_ec] = co_await conn.exec(req, check(), &diag); exec_ec)
        {
            print_err("Error issuing the LISTEN command", exec_ec, diag);
            continue;
        }

        // Read notifications. Logging is performed within the function,
        // so we don't need the result
        static_cast<void>(co_await read_notifications(conn));
    }

    // Try to close the connection gracefully.
    // Closing the connection may require I/O, and we want it to happen even
    // if we were requested cancel, so we use run with an empty stop_token.
    // Set a timeout to avoid hanging indefinitely
    static_cast<void>(co_await capy::run(std::stop_token())(capy::timeout(conn.shutdown(), 3s)));

    // Done
    co_return {};
}

// Waits for Ctrl+C (or SIGTERM)
static capy::io_task<> wait_for_signals()
{
    corosio::signal_set signals{(co_await capy::this_coro::executor).context(), SIGINT, SIGTERM};
    auto [ec, signum] = co_await signals.wait();
    if (!ec)
        std::cout << "\nReceived signal " << signum << "\n";
    co_return {};
}

static capy::task<> co_main()
{
    // Run the listener and the signal handler in parallel.
    // When a signal arrives, it cancels the listener.
    static_cast<void>(co_await capy::when_any(run_listener(), wait_for_signals()));
}

int main()
{
    // The I/O context, required for all I/O operations
    corosio::io_context ctx;

    // Schedules the main coroutine for execution
    capy::run_async(
        ctx.get_executor(),
        []() {
           // Runs when the main coroutine finishes normally
           std::cout << "Done\n";
        },
        [](std::exception_ptr exc) {
            // Runs when the main coroutine finishes with an exception
            try {
               std::rethrow_exception(exc);
            } catch (const std::exception& e) {
               std::cerr << "Error: " << e.what() << std::endl;
            }
            exit(1);
        }
    )(co_main());

    // Executes all pending work, including the main coroutine
    ctx.run();
}
