//
// Copyright (c) 2025 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef NATIVEPG_CO_CONNECTION_HPP
#define NATIVEPG_CO_CONNECTION_HPP

#include <boost/capy/buffers.hpp>
#include <boost/capy/concept/executor.hpp>
#include <boost/capy/ex/execution_context.hpp>
#include <boost/capy/io/any_stream.hpp>
#include <boost/capy/io_task.hpp>

#include <concepts>
#include <memory>
#include <optional>

#include "nativepg/connect_params.hpp"
#include "nativepg/encoding.hpp"
#include "nativepg/extended_error.hpp"
#include "nativepg/notification_vector.hpp"
#include "nativepg/protocol/connection_state.hpp"
#include "nativepg/request.hpp"
#include "nativepg/responses/response_handler.hpp"

namespace nativepg {

class exec_state;

class co_connection
{
    struct impl;
    std::unique_ptr<impl> impl_;

public:
    explicit co_connection(boost::capy::execution_context& ctx);

    template <class Ex>
        requires(!std::same_as<Ex, co_connection> && boost::capy::Executor<Ex>)
    explicit co_connection(const Ex& ex) : co_connection{ex.context()}
    {
    }

    co_connection(co_connection&&) noexcept;
    co_connection(const co_connection&) = delete;

    co_connection& operator=(co_connection&&) noexcept;
    co_connection& operator=(const co_connection&) = delete;

    ~co_connection();

    boost::capy::io_task<> connect(connect_params params, diagnostics* diag = nullptr);

    // Closes the connection (PQfinish)
    boost::capy::io_task<> shutdown();

    boost::capy::io_task<> exec(
        const request& req,
        response_handler_ref handler,
        diagnostics* diag = nullptr
    );

    template <response_handler ResponseHandler>
    boost::capy::io_task<> exec(const request& req, ResponseHandler handler, diagnostics* diag = nullptr)
    {
        // Keep the handler alive
        co_return co_await exec(req, response_handler_ref(&handler), diag);
    }

    // Waits until either a notification arrives, or an error occurs.
    // The connection must be in established state.
    // Received notifications are stored in output, which is cleared first.
    // Can be called in parallel with other exec() operations.
    // Only one receive() operation is allowed to be in-flight at any given time.
    //   Issuing another fails with client_errc::already_running.
    // If at least one notification is read, returns a non-empty error code.
    //   If an error condition is detected after some notifications have been read,
    //   they are returned, and no error is reported.
    boost::capy::io_task<> receive(notification_vector& output);

    // Prepares a request to be executed by the connection.
    // The passed exec_state becomes a handle for the operation that will be executed.
    // Once prepared, the request can be progressed by calling write_request (writer side) and
    //   read_some_response (reader side). Reader and writer may be run in parallel.
    // These functions respect multiplexing, and can be called in parallel with other exec() operations.
    //   If other requests are in-flight, these functions will wait appropriately until the connection is
    //   idle.
    // The exec_state, connection, request, handler and diagnostics must be kept alive
    // until all of its associated operations (reader and writer) complete.
    // If the request hasn't executed fully when the exec_state is destroyed
    //   (i.e. some output generated by the server hasn't been read yet),
    //   subsequent exec() operations will discard that output, and the connection will be kept healthy.
    // Subsequent requests can't make progress until you either read all the output generated by
    //   the server or destroy the exec_state.
    // Returns an error if request and handler are not compatible.
    [[nodiscard]] std::error_code prepare_request(
        exec_state& st,
        const request& req,
        response_handler_ref handler,
        diagnostics* diag = nullptr
    );

    // Writes the request pointed to by st to the server.
    // If another operation is currently writing requests (e.g. another parallel exec()),
    //   waits until its write part finishes before initiating the write.
    // Returns success if all the request's bytes were written to the server.
    //   In this case, st.write_finished() returns true.
    // If this function finishes with an error, the number of transferred bytes
    //   is stored internally within st. Subsequent write_request calls are allowed.
    //   This allows to resume writing after a cancellation, for example.
    // Only one instance of write_request for a given exec_state is allowed
    //   to be in-flight at a time. Attempting to launch another fails with client_errc::already_running.
    // Requires st.is_prepared() && !st.write_done().
    //   Otherwise, finishes with client_errc::invalid_state.
    boost::capy::io_task<> write_request(exec_state& st);

    // Reads part of the response generated by the server and invokes the response handler.
    // On success, reads a batch of messages from the server (unspecified size, at least one)
    //   and invokes the handler as required. Because not all messages involve handler invocation,
    //   read_some_response might invoke the handler zero times and still return success,
    //   meaning that it made progress.
    // If this function finishes with an error (including one matching capy::cond::canceled),
    //   you might call this function again to try to make more progress. The exec_state is updated
    //   as required to track progress.
    // Only one instance of read_some_response for a given exec_state is allowed
    //   to be in-flight at a time. Attempting to launch another fails with client_errc::already_running.
    // Requires st.is_prepared() && !st.read_done().
    //   Otherwise, finishes with client_errc::invalid_state.
    // This function is fully independent from write_request(). You are responsible
    //   for calling write_request() until st.write_done() return true.
    //   A failure in write_request() won't cancel read_some_response(), to allow re-trying.
    boost::capy::io_task<> read_some_response(exec_state& st);

    // Reads until there is at least one message in the read buffer.
    // Access messages with state().read_buffer
    boost::capy::io_task<> read_some_messages();

    // TODO: I don't like this
    boost::capy::any_stream& stream();
    protocol::connection_state& state();

    // Values reported via ParameterStatus
    std::optional<bool> standard_conforming_strings() const;
    std::optional<encoding> client_encoding() const;
};

}  // namespace nativepg

#endif
