//
// Copyright (c) 2025 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef NATIVEPG_ESCAPE_HPP
#define NATIVEPG_ESCAPE_HPP

#include <boost/compat/function_ref.hpp>

#include <string>
#include <string_view>
#include <system_error>

#include "nativepg/encoding.hpp"

namespace nativepg {

// TODO: are identifiers containing a NULL character truncated, or properly rejected by the server?

// Escapes a string to be used by an identifier.
// Calls fn successively with the string pieces generated by the escaping algorithm.
// The escaped identifier is the concatenation of all the pieces. The surrounding double quotes
// should be added by the caller.
std::error_code escape_identifier(
    std::string_view value,
    encoding enc,
    boost::compat::function_ref<void(std::string_view)> fn
);

template <class Traits, class Alloc>
std::error_code escape_identifier(
    std::string_view value,
    encoding enc,
    std::basic_string<char, Traits, Alloc>& to
)
{
    return escape_identifier(value, enc, [&to](std::string_view chars) {
        to.append(chars.data(), chars.size());
    });
}

}  // namespace nativepg

#endif
