//
// Copyright (c) 2025 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef NATIVEPG_ESCAPE_HPP
#define NATIVEPG_ESCAPE_HPP

#include <boost/compat/function_ref.hpp>

#include <string>
#include <string_view>
#include <system_error>

#include "nativepg/encoding.hpp"

namespace nativepg {

// Escapes a string to be used by an identifier.
// Calls fn successively with the string pieces generated by the escaping algorithm.
// The escaped identifier is the concatenation of all the pieces. The surrounding double quotes
// should be added by the caller (as opposed to PQescapeIdentifier).
// Values containing NULL bytes are rejected with client_errc::null_byte, as there is no way
// to safely escape a NULL byte without causing truncation.
// On error, the output is undefined - fn may be called any number of times with partial output.
// fn is never called with empty pieces.
[[nodiscard]]
std::error_code escape_identifier_body(
    std::string_view value,
    encoding enc,
    boost::compat::function_ref<void(std::string_view)> fn
);

// Appends the escaped identifier body to the passed string
template <class Traits, class Alloc>
[[nodiscard]]
std::error_code escape_identifier_body(
    std::string_view value,
    encoding enc,
    std::basic_string<char, Traits, Alloc>& to
)
{
    return escape_identifier_body(value, enc, [&to](std::string_view chars) {
        to.append(chars.data(), chars.size());
    });
}

// TODO: escape literal

}  // namespace nativepg

#endif
